### ISSUE TITLE
VS 2013 does not support `default` for move constructors

### ISSUE THREAD

**Issue by vladon** [iwongu/sqlite3pp#17]
While using sqlite3pp in VS 2013 (yeah, old, but still in widely use) the compiler generates next errors:

````
2>C:\work\tmclient\common\libs\sqlite3pp\sqlite3pp.h(57): error C2610: 'sqlite3pp::noncopyable::noncopyable(sqlite3pp::noncopyable &&)' : is not a special member function which can be defaulted
2>C:\work\tmclient\common\libs\sqlite3pp\sqlite3pp.h(58): error C2610: 'sqlite3pp::noncopyable &sqlite3pp::noncopyable::operator =(sqlite3pp::noncopyable &&)' : is not a special member function which can be defaulted
````

Error points to sqlite3pp.h, lines 57 & 58:

````cpp
    noncopyable(noncopyable&&) = default;
    noncopyable& operator=(noncopyable&&) = default;
````

See also [similar question on stackoverflow](http://stackoverflow.com/questions/24573963/move-constructor-invalid-type-for-defaulted-constructor-vs-2013)

Can you please fix it?

**Comment by iwongu** [comment]
Alternatively, you can use the code in /boost_src. It requires boost library but it can be used pre-c++1x compilers.

**Comment by iwongu** [comment]
Please reopen if the solution didn't fix your problem.
