### ISSUE TITLE
throwing destructors

### ISSUE THREAD

**Issue by vladon** [iwongu/sqlite3pp#18]
Destructors in C++11 are implicitly have nothrow specification, and cannot throw.

```
1>..\..\common\libs\sqlite3pp\sqlite3pp.cpp(195): warning C4297: 'sqlite3pp::statement::~statement': function assumed not to throw an exception but does
1>  ..\..\common\libs\sqlite3pp\sqlite3pp.cpp(195): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>..\..\common\libs\sqlite3pp\sqlite3pp.cpp(494): warning C4297: 'sqlite3pp::transaction::~transaction': function assumed not to throw an exception but does
1>  ..\..\common\libs\sqlite3pp\sqlite3pp.cpp(494): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
```

**Comment by iwongu** [comment]
I think we have two options.
One is adding nothrow(false) in the dtors.
Another is not throwing exceptions in the dtors. It just ignores the errors in dtors. If users want to check the errors, they need to call commit (for transaction) or finish (for statement, that is, command and query) explicitly and check the return value.

Any input for the options?

**Comment by iwongu** [comment]
I added noexcept(false) in the dtors throwing exceptions.
