### ISSUE TITLE
statement doesn't have a bind(int, std::string)

### ISSUE THREAD

**Issue by ReallyNiceGuy** [iwongu/sqlite3pp#19]
Hi, what is the reasoning behind that missing bind function?
I would do:
```cpp
int statement::bind(int idx, const std::string& value)
{
  return sqlite3_bind_blob(stmt_, idx, value.c_str(), value.size(),  SQLITE_TRANSIENT);
}
```

**Comment by Zzzen** [comment]
yeah, why not?

**Comment by iwongu** [comment]
Frankly, I don't remember exactly why I didn't include the string version of function. :)
It seems that there is no harm to add it now.

int bind(int idx, const string& value, bool fstatic = true);

If the string is deallocated before query is executed, you should set false for fstatic.

**Comment by iwongu** [comment]
Can you check this change if it's okay for you guys?

https://github.com/iwongu/sqlite3pp/commit/e5dd11c78b7bbc56c27dbfd018e18f64bf978b27

**Comment by ReallyNiceGuy** [comment]
I would think that fstatic equals false is safer. My personal view is that
no default is even better because it forces the user to select the correct
case every time.

**Comment by iwongu** [comment]
Yes, I agree that safer better than faster. But, I already used fstatic=true for other bind functions. If I used a different default value for string bind one, it might be more confusing.

**Comment by ReallyNiceGuy** [comment]
So can I make a patch later changing everything from default=true to no
default?

We might need to bump the major version for that.

**Comment by iwongu** [comment]
It'll break existing code but should be easy to fix. So, I'm fine with it.
When we make the change, I want to rename the parameter to *fcopy* or something more obvious.
Anyway, let me merge this change into the main branch.

**Comment by ReallyNiceGuy** [comment]
Ok, I will do it today.
