### ISSUE TITLE
Changing the meaning of bool values is a bad idea

### ISSUE THREAD

**Issue by jpetso** [iwongu/sqlite3pp#22]
In https://github.com/iwongu/sqlite3pp/commit/b7800951a92bedbc3a5cf37b57245153342e09ed the `fstatic` parameter has been renamed to `fcopy`, which in itself is probably better API but is really dangerous for people who already use a previous version and want to upgrade.

All the people who have previously passed `true` as `fstatic` will still pass `true` after updating to your newest version, and then their code will be broken. Fixing it would require inspecting every single bind call, and is error prone as heck.

Instead of reversing the boolean, a better approach would be to make it an enum. For instance I would call:
```C++
const char* str1 = "foo";
std::string str2 = "foo";
stmt.bind(0, str1, strlen(str1), sqlite3pp::reference);
stmt.bind(1, str2, str2.size(), sqlite3pp::copy);
```
This has two benefits:
* It provides a compiler error to upgrading developers, instead of silently breaking their programs.
* It's also much more readable than any of the previous two versions, so I know what it does without even looking up the function in the header file.

Please fix this and save your existing users from segfaults.

**Comment by iwongu** [comment]
Jakob, I agree.
Can you check this commit and give some feedback?
https://github.com/iwongu/sqlite3pp/commit/8583f2d5569fef326ab8649c4ac58bb2f66337ed

**Comment by jpetso** [comment]
That seems fine, yes. Thank you!
