### ISSUE TITLE
Unable to catch "sqlite" database exceptions

### ISSUE THREAD

**Issue by djvoracious** [iwongu/sqlite3pp#23]
Hi there, I have started playing around with this but I have noticed that when there is a exception at the sqlite level, all exceptions are impossible to catch, regardless of whether or not they are in a try/catch. This is causing the app to crash. 

An example is when trying to insert a record with duplicate key. It just dies. Is there a way to handle these? Rather than doing a lookup before doing the  insert?

**Comment by iwongu** [comment]
http://stackoverflow.com/a/29973130
