### ISSUE TITLE
`cmd.binder() << "Mike";` doesn't work

### ISSUE THREAD

**Issue by Zzzen** [iwongu/sqlite3pp#25]
Since `int Statement::bind(int idx, char const* value, bool fstatic = true);` has been changed to `int Statement::bind(int idx, char const* value, copy_semantic fcopy);`. I would prefer `fcopy=copy`.

**Comment by iwongu** [comment]
Ouch, I forgot why I did put the default value for the extra param in bind methods.
I'm going to add back the default value. I'm thinking 'copy' for string and 'nocopy' for pointers
@ReallyNiceGuy @jpetso

**Comment by iwongu** [comment]
Actually, I didn't have to add the default values back. I just added binder operator overloading for 'char const*' and 'string const&' types.
https://github.com/iwongu/sqlite3pp/commit/b7710652b971bb816ec426f7907eae38a9a389da
