### ISSUE TITLE
What is the current stable version?

### ISSUE THREAD

**Issue by giumas** [iwongu/sqlite3pp#28]
I am having troubles to identify a version of this library to pair it with the last changes. Is this a missing feature?

**Comment by iwongu** [comment]
This library is not having versions yet. The latest commit is supposed to be stable one.

**Comment by giumas** [comment]
What about adding something pretty simple like this:

```
#define SQLITE3PP_VERS_MAJ 1	// version major
#define SQLITE3PP_VERS_MIN 0	// version minor
#define SQLITE3PP_VERS_FIX 0	// version fix
```

on top of https://github.com/iwongu/sqlite3pp/blob/master/src/sqlite3pp.h ?

**Comment by iwongu** [comment]
Maybe version tagging is better?

**Comment by giumas** [comment]
I assume that you mean git tags. I believe that both approaches should be used together. SQLite does both: in ``SQLite.h``, there is ``#define SQLITE_VERSION        "3.X.X"``. Otherwise, once that a developer has decided to include the ``sqlite3pp`` code in his project, how could he checks the version?

**Comment by iwongu** [comment]
Right. Let me work on it soon.

**Comment by iwongu** [comment]
I added the version info in header file and tag current commit as "v1.0.0".

#define SQLITE3PP_VERSION "1.0.0"
#define SQLITE3PP_VERSION_MAJOR 1
#define SQLITE3PP_VERSION_MINOR 0
#define SQLITE3PP_VERSION_PATCH 0

**Comment by giumas** [comment]
Great! Thank you

**Comment by iwongu** [comment]
My pleasure, and thanks for the great suggestion.
