### ISSUE TITLE
database file is locked even after database::disconnect

### ISSUE THREAD

**Issue by kozhevnikovandrey** [iwongu/sqlite3pp#29]
The bug in your code:

  int database::disconnect()
  {
    int rc = SQLITE_OK;
    if (db_) {
      rc = sqlite3_close(db_);
      db_ = 0;
    }
    return rc;
  }

if sqlite3_close returned an error, db_ becomes NULL and database never closed.

Probably, you should add rc check
      if (rc == SQLITE_OK)
        db_ = 0;

**Comment by iwongu** [comment]
https://github.com/iwongu/sqlite3pp/commit/011c3f570760a6df92e042a6ba09654867c79546

Thanks for reporting!
