### ISSUE TITLE
query::begin() is a misnomer

### ISSUE THREAD

**Issue by jpetso** [iwongu/sqlite3pp#30]
My coworker just spent a few hours trying to find out why he was getting a crash from this innocuous block of code:

```C++
sqlite3pp::query qry(...);
// not listed: initializing the statement, binding variables

if (qry.begin() != qry.end()) {
    sqlite3pp::query::iterator it = qry.begin();
    do_stuff((*it).get<std::string>(0)); // this crashes despite being declared as TEXT NOT NULL
}
```

As the author who has dealt with SQLite extensively, you might quickly be able to tell what's going on there:
* `query::begin()` is implemented as "create query_iterator, which calls `sqlite3_step()` in its constructor". 
* If `query::begin()` is called twice, this will just call `sqlite3_step()` a second time, which means `it` is at an invalid row now because the result only had a single row.

If I write the same code using `sqlite_*()` functions, I won't make this error. However, by using `begin()` as an alias for `step()`, you implement a well-defined C++ concept with unexpected (one might say wrong) behavior. Popular libraries teach us that we can have as many iterators as we want, they're all independent from each other as long as the underlying structure isn't changed, and `begin()` always gives you the first element.

In the current code, this behavior is more similar to Java's `next()`/`hasNext()` than C++'s `begin()`/`end()`. It appears SQLite doesn't really allow you to have multiple iterators/cursors for the same prepared statement, so the best course of action would be to rename `begin()` so people don't expect the wrong things from it.

My suggestion would be to rename it to `execute()` (the same name that `command` is using as well) but unlike `command`, let it continue returning the iterator. The `query_iterator` constructor would call `sqlite3_reset()` before calling `sqlite3_step()`. Everything else from then on would stay the same, `end()` does match the established C++ semantics so I think it's okay to leave it with its current name. The resulting code would then look like this:

```C++
sqlite3pp::query::iterator it = qry.execute();
if (it != qry.end()) {
    do_stuff((*it).get<std::string>(0)); // this crashes despite being declared as TEXT NOT NULL
}
```

and the code from the current README.md example also still makes sense:

```C++
for (sqlite3pp::query::iterator i = qry.execute(); i != qry.end(); ++i) {
  for (int j = 0; j < qry.column_count(); ++j) {
    cout << (*i).get<char const*>(j) << "\t";
  }
  cout << endl;
}
```

In addition, my coworker's original code would clearly indicate what it's doing:

```C++
if (qry.execute() != qry.end()) { // first execution of the query
    sqlite3pp::query::iterator it = qry.execute(); // second execution of the query
    // reset() doesn't clear bindings, so the second execution still behaves as expected.
    do_stuff((*it).get<std::string>(0)); // doesn't crash, only needlessly inefficient
}
```

Because it's clear that it's doing the wrong thing, it would probably never get written this way - but even in this form, it behaves as the developer would expect it to behave.

Either way, `begin()` deserves to be deprecated or removed. Thank you for your time and patience :)

**Comment by iwongu** [comment]
Similar issue to https://github.com/iwongu/sqlite3pp/issues/2 except that it's using input_iterator_tag in non boost versions.

If there is a better way to say that a container can be iterated only once (single pass), it would be great. But, input_iterator_tag is closest one that I could find.

Even though it's not exactly doing what other begins do, I prefer keeping begin/end pair instead of execute/end one which might be more correct but less beautiful.

**Comment by jpetso** [comment]
Beautiful is nice, but I don't believe it's worth to make code more beautiful when it comes at the expense of misleading developers into writing buggy code.

My view is that real beauty in code comes from simple, intuitive and consistent abstractions that allow developers to not consider underlying implementation details. sqlite3pp's implementation of `begin()`/`end()` offers fake simplicity: It promises a standard interface that people know how to use, but then negates the user's existing knowledge and turns it against him by behaving differently. If every library took the freedom to redefine well-known names and concepts with arbitrary overloads, these names and concepts would become meaningless. Instead of seeing an API and using it, I'd have to double-check in the API documentation all the time to make sure it does what I want.

This is not healthy; standards exist to save the developer some work, not to add more work. In order to save effort, I need to be able to trust that whenever I see a certain standard pattern, its implementation works according to standard behavior.

`input_iterator_tag` is the right concept to use: It describes a read-only iterator, it doesn't say that the iterator is bi-directional, it also doesn't say that the iterator can be reset to any other element except the next one. It says that the iterator can be used for a single pass, and nothing else on top of it.

`input_iterator_tag` is also not the issue at hand here: It [applies to an iterator, not to a container](http://en.cppreference.com/w/cpp/iterator/iterator_tags). Once you have an iterator, everything's fine.

This issue is concerned how you can get an initial iterator. A method like `execute()` (or `next()` if you prefer that idiom) is better than `begin()` because it makes life easier for developers in two ways:
* It tells them that the behavior is different than standard `begin()`/`end()`, so they know to pay attention and write correct code.
* It doesn't destroy assumptions, so the developer can use `begin()`/`end()` from other libraries without getting paranoid.

Other than that, that the iterator that you get from an `execute()` or `next()` function is still a first-class, real, awesome iterator. Renaming `begin()` doesn't subvert the concept of the iterator. You can still use that iterator, and the sentinel iterator that you get from `end()`, with standard algorithms and generic functions. People can trust the iterator to do what it's supposed to, because you implemented it with standard iterator behavior.

As a developer, I want to be able to read code and immediately know what it's doing. I want to be able to read code and be able to tell that it's correct. That's beautiful code. Everything else is just icing on the cake.

**Comment by iwongu** [comment]
I've been thinking about this and decided not to change the name.
I still prefer having the conventional begin/end pair even though it's misleading in some edge cases.

Also begin/end pair allows clients to use range based loop like this.
`for (auto v : qry) { ... }`
