### ISSUE TITLE
 access to the sqlite3* pointer inside class database

### ISSUE THREAD

**Issue by yongthecoder** [iwongu/sqlite3pp#31]
There are many sqlite3 features that are not supported by sqlite3pp::database. As a workaround, it would be nice if user can use the internal sqlite3* pointer.

Some useful features that are not supported;
1. sqlite3_changes(): tell how many rows are changed.
2. sqlite3_extended_errcode(): can be used to route errors based on more detailed classification.

**Comment by iwongu** [comment]
What if we add the useful methods in database class like enable_foreign_keys() or error_code() instead of exposing internal pointer?

**Comment by iwongu** [comment]
Added the methods. Let me know if you need more methods like these.

https://github.com/iwongu/sqlite3pp/commit/d755c07eba3cd623679ad30033aae343768b3bbe

**Comment by yongthecoder** [comment]
adding methods is always good. But there are many sqlite3 functions that I am afraid won't all be supported in sqlite3pp any time soon. Exposing internal pointer is not neat, but who uses it should be at his own risk.

**Comment by iwongu** [comment]
Do you have a list of functions in mind? I still prefer hiding the internal pointer in private.

**Comment by yongthecoder** [comment]
For now, I think changes() and extended_error_code() will be helpful

**Comment by iwongu** [comment]
As I wrote, they are already added in https://github.com/iwongu/sqlite3pp/commit/d755c07eba3cd623679ad30033aae343768b3bbe
Git-pull to see them.
