### ISSUE TITLE
SQLite Online Backup API

### ISSUE THREAD

**Issue by calumr** [iwongu/sqlite3pp#35]
I had to use SQLiteCpp as it provides a wrapper for sqlite3_backup_init, but I'd prefer to use sqlite3pp! 

https://github.com/SRombauts/SQLiteCpp/blob/master/include/SQLiteCpp/Backup.h

**Comment by calumr** [comment]
https://www.sqlite.org/backup.html

**Comment by iwongu** [comment]
It seems useful feature. Let me make a proposal change soon.

**Comment by iwongu** [comment]
@calumr Can you check this branch? I added backup methods in database class.

https://github.com/iwongu/sqlite3pp/commit/75ab17c3ecb0a3817ccfda3f82a0fb3cf38a188e

**Comment by iwongu** [comment]
https://github.com/iwongu/sqlite3pp/releases/tag/1.0.5
