### ISSUE TITLE
Will add unicode support?

### ISSUE THREAD

**Issue by nidilong** [iwongu/sqlite3pp#39]
This is a great and easy use library,and will you add unicode to it?

**Comment by iwongu** [comment]
Can you be more specific what unicode support means?

**Comment by nidilong** [comment]
Some sqlite3 functions like 'sqlite3_open16' and so on

**Comment by iwongu** [comment]
Let me wait until more requests come for UTF-16. BTW, are you using UTF-16 for your projects? Just for curious.

**Comment by nidilong** [comment]
yes, our projects are UTF-16, feels bad.
