### ISSUE TITLE
Wrong version in 1.0.5 package

### ISSUE THREAD

**Issue by nk1973** [iwongu/sqlite3pp#40]
You have wrong version in sqlite3pp.h in sqlite3pp-1.0.5.tar.gz
#define SQLITE3PP_VERSION "1.0.0"
#define SQLITE3PP_VERSION_MAJOR 1
#define SQLITE3PP_VERSION_MINOR 0
#define SQLITE3PP_VERSION_PATCH 0

As i understand it should be 1.0.5? (SQLITE3PP_VERSION_PATCH == 5?)

**Comment by iwongu** [comment]
Thanks. I forgot that the file has the version number definitions. :)
I set it in https://github.com/iwongu/sqlite3pp/releases/tag/v1.0.6 release with correct version numbers.
