### ISSUE TITLE
Compiling on Ubuntu error

### ISSUE THREAD

**Issue by pabloaotero** [iwongu/sqlite3pp#41]
Hi! Nice library. I have used it on windows (VS 2015) and now I'm using on Ubuntu (Netbeans 8.1). 
When I try to compile it i get this error:

sqlite3pp.h:191:40: error: call of overloaded ‘bind(int&, long int&)’ is ambiguous

Any idea about it?

Thank you very much.

**Comment by ntfshard** [comment]
Hello

As far as I understand you trying to call `operator <<` with variable type=`long int`;
As you can see in sqlite3pp.h:147-163 there are no overload for `int, long int`

You can try to use `static_cast<int>(your_variable)`

**Comment by iwongu** [comment]
Try 'long long int' or 'int' instead of 'long int'. Sorry for very late response.
