### ISSUE TITLE
Move semantics for query?

### ISSUE THREAD

**Issue by andreygorbachev** [iwongu/sqlite3pp#42]
Hi,

Looks like (noncopyable) sqlite3pp::database class have move constructor and move assignment operators, so we can do:

auto db = sqlite3pp::database{ ..... };

Should the sqlite3pp::query have the same? (and maybe other noncopyables types in sqlite3pp?) So we could do:

auto q = sqlite3pp::query{ ..... };

I am trying to see how well "Almost Always Auto" would work:
https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

Thanks,
Gorby

**Comment by iwongu** [comment]
I'm not sure that `AAA` is always a good pattern to follow.
I don't think sqlite3pp classes would be beneficial from following the rule "write code against interfaces, not implementations".
If you have a stronger opinion, please let me know. I'll consider it as an option. Though I'm not a big fan of giving as many options as possible.
