### ISSUE TITLE
query::rows::get(...) implementation for std::string type crashes on NULL

### ISSUE THREAD

**Issue by ediap** [iwongu/sqlite3pp#48]
In case when returned "const char*" value points to nullptr, the following implementation crashes. Is this expected implementation and the client code is requested to not use this wrapper for possible NULL values?
```
  std::string query::rows::get(int idx, std::string) const
  {
    return get(idx, (char const*)0);
  }
```

**Comment by iwongu** [comment]
Yes, if it can be NULL, please use char const* version instead of string one.
