### ISSUE TITLE
library without boost

### ISSUE THREAD

**Issue by peterritter** [iwongu/sqlite3pp#5]
Hi
I love your library - just what I needed,... but I can't use boost. I have a large project that does not use boost and I can't add it now just for this. I think a lot of what you use boost for is now part of the standard c++ library, like std::tuple, std::function, and most compilers are now C++11. I really think you should try to get rid of boost. I tried to give it a shot, but got stuck on the iterator part. I will try to see if the boost headers are 'header only' - maybe I can include them in my library that way. 
Any thoughts on this? 

Best Regards, Peter

**Comment by iwongu** [comment]
Peter,
Thanks for your suggestion. I also think that it would be great if sqlite3pp can be used without any other 3rd party dependencies.
IIRC, it's not using only header files from boost.
Unfortunately, I'm using another programming languages, so I wasn't following what are in C++1x exactly. So, it might take some time but let me try as soon as possible.

**Comment by peterritter** [comment]
Hello Wongoo

Thanks for the reply!   C++11 is great! There are some really wonderful
additions like <chrono>, <thread>, <memory> (for managed pointers).
<functional> for function pointer abstraction as well as the addition of
lambda functions to the language itself!
I think the only real work in your library is to get rid of the boost
iterator aspects.

Best Regards, Peter Ritter

**Comment by iwongu** [comment]
fyi, I found that all boost codes here are 'header-only' library.

**Comment by iwongu** [comment]
Now, you can use sqlite3pp.h and sqlite3pp.cpp without using boost. Checkout noboost_src directory in noboost branch.
For the sqlite3ppext.h and cpp, I'm still working on it.

**Comment by iwongu** [comment]
All done for ext files too.

**Comment by peterritter** [comment]
Hello Wongoo

thank you so much for updating your library to avoid boost. It all looks so
different now. Nice job - thank you!

Best Regards, Peter Ritter
