### ISSUE TITLE
iterator fix

### ISSUE THREAD

**Issue by anders43** [iwongu/sqlite3pp#57]
Hi
In order to compile the code with C++17 a fix needs to be done to the iterator, here is the fix:
[fixiterator-STL4015.zip](https://github.com/iwongu/sqlite3pp/files/2941780/fixiterator-STL4015.zip)

HTH
Anders.

**Comment by anders43** [comment]
I have not updated the boost part since I don't have that installed.

**Comment by iwongu** [comment]
Can you send a pull request instead?

**Comment by anders43** [comment]
I will try again tonight. I had some access denied msg. Br anders

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
