### ISSUE TITLE
Can not build with Visual Studio 2013

### ISSUE THREAD

**Issue by jeremynealbrown** [iwongu/sqlite3pp#6]
Using a fresh clone of the source code, I see two errors when attempting to build with Visual Studio 2013.

sqlite3pp.cpp Line 49
```Error C2146: syntax error : missing ';' before identifier 'noncopyable'```

sqlite3pp.cpp Line 49
```Error C4430: missing type specifier - int assumed. Note: C++ does not support default-int```

Test code looks like this:
```
#include "sqlite3pp.h"

class MyApp {
public:
    sqlite3pp::database db;
    void setup();    
}

void MyApp::setup() {
    db.connect("test.sqlite");
}
```

**Comment by jeremynealbrown** [comment]
Looks like 4430 is just a warning that can ignored.

**Comment by iwongu** [comment]
I found this. :(
http://stackoverflow.com/questions/20264644/constexpr-not-compiling-in-vc2013
Let me remove constexpr from the code.
Thanks for reporting this.

**Comment by iwongu** [comment]
Done.

**Comment by jeremynealbrown** [comment]
Very nice. Thanks for taking the time to do that.
