### ISSUE TITLE
Query iterator has unexpected side effects

### ISSUE THREAD

**Issue by eugene-kulak** [iwongu/sqlite3pp#64]
Currently, if you call `begin` two or more times you will skip records as the cursor will be moved every time. This is not how `begin` should behave and definitely not what most people expect from. Typical use case - check if the result has any rows

```cpp
qry.begin() != qry.end()
```

and then iterate

**Comment by iwongu** [comment]
It's unfortunate to have this limitation. I used the std::input_iterator_tag to tell that it's a single pass iterator.
