### ISSUE TITLE
how to insert a NULL value ?

### ISSUE THREAD

**Issue by Becheler** [iwongu/sqlite3pp#68]
Hi! Thank you for this library!
I wanted to know the syntax  i could use to insert a NULL value in a database ? For now I insert an empty string using:

    sqlite3pp::command cmd(
      this->m_database,
      "INSERT INTO table (a, b, c) VALUES (?,?,?)"
    );
    cmd.binder() << a << b << "";
    cmd.execute();

Thank you!

**Comment by iwongu** [comment]
It was possible to bind nullptr using bind(), but not binder(). I just added the nullptr binding in binder(). You can do

`cmd.binder() << nullptr;`
