### ISSUE TITLE
Add a method wrapping `sqlite3_clear_bindings`

### ISSUE THREAD

**Issue by snej** [iwongu/sqlite3pp#70]
The `statement::reset` method calls `sqlite3_reset`, which makes the `sqlite3_stmt` ready to run again, but does _not_ clear bindings. That means if you run the statement again but don't re-bind every parameter, some of the old bindings stay in effect.

There should be a method that calls `sqlite3_clear_bindings`, to ensure that all bindings are restored to `null`.

**Comment by iwongu** [comment]
I added the clear_bindings() in statement class. Sorry for the long delay.
