### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MasterDrake** [iwongu/sqlite3pp#72]
Hi, can you please add a license.md ?
I saw in the code that it's should be licensed under MIT, adding a license.md should be straightforward and optimal for everyone.
Thanks!

**Comment by iamazeem** [comment]
@iwongu: Great work! :+1: Could you please add an MIT license to the project's root? Thanks!

**Comment by iwongu** [comment]
A little late, but done now.

**Comment by MasterDrake** [comment]
Thank you, I tried to find a way to contact you with no luck
Glad you're still rockin' :)
