### ISSUE TITLE
sqlitepp::database construct  error with  memory leak?

### ISSUE THREAD

**Issue by snoopyIV** [iwongu/sqlite3pp#73]
I had a question with the constructor of sqlite3pp::database obeject.
The `sqlite_open_v2()` function is called in  by  function `sqlite3pp::connect()` in file sqlite3pp.ipp. It means also called by sqlite3pp::database constructor function.
``` c++
  database::database(char const* dbname, int flags, char const* vfs) : db_(nullptr), borrowing_(false)
  {
    if (dbname) {
      auto rc = connect(dbname, flags, vfs);                      ///< sqlite3_open_v2() is called here
      if (rc != SQLITE_OK)                                                   
        throw database_error("can't connect database");   ///< if exception throws, sqlite3_close() will not called
    }
  }
```

But if there is error occured, like a illegal path, the constructor function will throw exception. And sqlite3_close() function will not called, which was contrary to sqlite3 docs(https://www.sqlite.org/capi3ref.html#sqlite3_open). Sqlite3 docs declares： Whether or not an error occurs when it is opened, resources associated with the [database connection](https://www.sqlite.org/capi3ref.html#sqlite3) handle should be released by passing it to [sqlite3_close()](https://www.sqlite.org/capi3ref.html#sqlite3_close) when it is no longer required.

In fact , I can catch exception and csalled sqlite3_close() by myself. But I need to get raw sqlite3 obeject managerd by sqlite3pp. I don't know if it was designed, or there is better way to solve this question?
Thanks for help!

By the way, I tried use illegal path to make exceptions while constructing. It did have some memory leak, perhaps 70-100KB each 100 times if I  did not called sqlite3_close(). The  enviroment is win10, vs2015.

**Comment by iwongu** [comment]
Good catch! I just pushed the change to close the db if the open is failed in the ctor.
