### ISSUE TITLE
Support for sqlite3_column_text16

### ISSUE THREAD

**Issue by pwdMark** [iwongu/sqlite3pp#77]
Does sqlite3pp API supports sqlite3_column_text16 ?  Does it plan to support sqlite3_column_text16 ? Please clarify. Thank you!

**Comment by stewbond** [comment]
The upstream C API is used in `sqlite3pp.ipp`.  There are no references to `sqlite3_column_text16()` in there.  Only `sqlite_column_text()`.

But I can see how this could be easy to add: 

```
  inline char const* query::rows::get(int idx, char16_t const*) const
  {
    return reinterpret_cast<char16_t const*>(sqlite3_column_text16(stmt_, idx));
  }
```

**Comment by pwdMark** [comment]
Thank you!  Is there any plan to add the support for char16_t to query::rows::get and statement::bind in future release ?

**Comment by iwongu** [comment]
get() and bind() added. please let me know if it has issues.
